trigger_topic_name: "/trigger"
rgb_topic_name: "/kinect2_head/rgb/image"
depth_topic_name: "/kinect2_head/depth/image"
rgb_info_topic_name: "/kinect2_head/rgb/camera_info"
depth_info_topic_name: "/kinect2_head/depth/camera_info"